forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'

mod "jenkins",
  :git => "git://github.com/jenkinsci/puppet-jenkins.git"

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "puppetlabs/firewall"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/git'

mod 'erikwebb/drush'

mod 'puppetlabs/apache'
mod 'puppetlabs/mysql'
mod 'thias/php'
mod 'ScarceMedia/imagemagick'
