name    'erikwebb-drush'
version '0.0.2'
source 'git://github.com/erikwebb/erikwebb-drush.git'
author 'erikwebb'
license 'Apache License, Version 2.0'
summary 'Drush Puppet Module'
description 'A Puppet module to install and execute Drupal commands using Drush.'
project_page 'http://github.com/erikwebb/erikwebb-drush'

dependency 'rafaelfc/pear'
